language: scala
sudo: false

scala:
  - 2.12.8

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

# Taken from https://github.com/typelevel/cats/blob/master/.travis.yml
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

